CREATE DATABASE SHOPDB;

USE SHOPDB;

CREATE TABLE PRODUCT(
ID INTEGER PRIMARY KEY,
NAME_P varchar(30),
PRICE DOUBLE,
CATEGORY ENUM('FOOTWEAR','TEXTILE','ACCESSORY'),
STOCK INT,
ROOT VARCHAR(30)
);

CREATE TABLE CLIENT_S(
ID INTEGER PRIMARY KEY,
NAME_C VARCHAR(30),
EMAIL VARCHAR(30),
PHONE CHAR(9),
ADDRESS VARCHAR(30)
);